### ISSUE TITLE
Add more elaborate block breaking

### ISSUE THREAD

**Issue by Inspirateur** [Inspirateur/riverbed#11]
Blocks shouldn't break instantly, have various hardness levels, and there should be appropriate tools to break them. 

What blocks yield upon breaking should also be dependent on the tool used to break them.

These values should be configurable via a config file such as .toml so they can be edited without recompiling

- [x] 1. Figure out a good format for the config
- [x] 2. Implement deserialization into a Bevy Resource
- [x] 3. Implement breaking with hardness
- [x] 4. Implement looting (blocked by #12)

## Current format choice 
[JSON5](https://json5.org/)
```json5
{
    Default: {
        Stone: { hardness: 7, drops: "Rock", min: 4, max: 6 }, 
        Limestone: { hardness: 5.5, drops: "Lime", min: 1, max: 2 },
        Log: { hardness: 5, drops: "Stick", min: 2, max: 3 }, 
        // will fallback on 'log' family for the other info
        Acacialog: { hardness: 6 },
        // if no drop quantity is specified it defaults to 1
        Soil: { hardness: 3, drops: "Self" },
        Sand: { hardness: 1.5 },
    },
    Shovel: { 
        Soil: { hardness: 1.5 }, 
        Sand: { hardness: 0.75 },
    },
    Pickaxe: { 
        Stone: { hardness: 2.5, drops: "Self" }, 
        Glass: { hardness: 1 },
    },
    Axe: {
        // you get the idea
    },
}
```
Limitations: 
- this syntax only allows blocks to drop 1 type of stuff, but it can be extended

*see discussion below (with myself 🤪) for other ideas and pros/cons*

**Comment by Inspirateur** [comment]
Some blocs will have the same hardness/yield properties (like wood types), or will have the same preferred tool (like rocks) so having a way to group blocs into families to write the config files would be really useful.

**Comment by Inspirateur** [comment]
Ok here's a first draft (with example data):
```toml
# blocks are allowed to be in 0, 1 or more families !
[block_family]
stone = ["cobblestone", "stone", "limestone"]
soil = ["dirt", "sand", "mud", "snow"]
log = ["oaklog", "birchlog", "sequoialog"]
leaves = ["oakleaves", "birchleaves", "sequoialeaves"]
glass = ["glass", "ice"]

# unspecified hardness will make the block unbreakable (eg bedrock)
[hardness]
# block hardness when no tool is used (also fallback values if the tool did not specify the hardness for a block)
# both block families and block can be specified (the block will take precedence over the block family)
default = {
  stone = 7, limestone = 5.5,
  log = 5, acacialog = 6,
  soil = 3, sand = 1.5
}

shovel = { soil = 1.5, sand = 0.75 }

# limestone is specified directly in 'default' and only 'stone' is specified here but hardness 2.5 will be chosen if the player breaks a limestone with a pickaxe (tool takes precedence)
pickaxe = { stone = 2.5, glass = 1. }

# we could image the pebble being a tool, prompting the player to look for one at the beginning
pebble = { stone = 4, limestone = 3, log = 3 }

# unspecified loot means the block will loot nothing upon breaking
[loot]
default = {
  stone = [4, 6, "pebble"],
  limestone = [1, 2, "lime"], 
  log = [1, 2, "stick"]
}

# really not sure about this syntax, how should we specify that a bloc will drop itself ?
pickaxe = { stone = [1, "self"] }
```
It's probably very flawed, so feedback is welcome :)
